// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/tnozicka/openshift-acme/pkg/client/operator/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ACMEControllers returns a ACMEControllerInformer.
	ACMEControllers() ACMEControllerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ACMEControllers returns a ACMEControllerInformer.
func (v *version) ACMEControllers() ACMEControllerInformer {
	return &aCMEControllerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
