// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/tnozicka/openshift-acme/pkg/api/acme/v1"
	"github.com/tnozicka/openshift-acme/pkg/client/acme/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AcmeV1Interface interface {
	RESTClient() rest.Interface
	ACMEControllersGetter
}

// AcmeV1Client is used to interact with features provided by the acme.openshift.io group.
type AcmeV1Client struct {
	restClient rest.Interface
}

func (c *AcmeV1Client) ACMEControllers() ACMEControllerInterface {
	return newACMEControllers(c)
}

// NewForConfig creates a new AcmeV1Client for the given config.
func NewForConfig(c *rest.Config) (*AcmeV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &AcmeV1Client{client}, nil
}

// NewForConfigOrDie creates a new AcmeV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AcmeV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AcmeV1Client for the given RESTClient.
func New(c rest.Interface) *AcmeV1Client {
	return &AcmeV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AcmeV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
