// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/tnozicka/openshift-acme/pkg/api/acme/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ACMEControllerLister helps list ACMEControllers.
// All objects returned here must be treated as read-only.
type ACMEControllerLister interface {
	// List lists all ACMEControllers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ACMEController, err error)
	// Get retrieves the ACMEController from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ACMEController, error)
	ACMEControllerListerExpansion
}

// aCMEControllerLister implements the ACMEControllerLister interface.
type aCMEControllerLister struct {
	indexer cache.Indexer
}

// NewACMEControllerLister returns a new ACMEControllerLister.
func NewACMEControllerLister(indexer cache.Indexer) ACMEControllerLister {
	return &aCMEControllerLister{indexer: indexer}
}

// List lists all ACMEControllers in the indexer.
func (s *aCMEControllerLister) List(selector labels.Selector) (ret []*v1.ACMEController, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ACMEController))
	})
	return ret, err
}

// Get retrieves the ACMEController from the index for a given name.
func (s *aCMEControllerLister) Get(name string) (*v1.ACMEController, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("acmecontroller"), name)
	}
	return obj.(*v1.ACMEController), nil
}
