// Code generated by lister-gen. DO NOT EDIT.

package v1

// ACMEControllerListerExpansion allows custom methods to be added to
// ACMEControllerLister.
type ACMEControllerListerExpansion interface{}
